// Regenerates src/lib/offCategories.ts, the category suggestions offered in
// the rule editor, from the Open Food Facts category taxonomy.
//
//   npm run categories:build                      downloads the taxonomy (~5 MB)
//   npm run categories:build -- categories.json   uses a copy already on disk
//
// Not part of `npm test`; run it when the suggestions feel out of date.
import { readFileSync, writeFileSync } from "node:fs";

const TAXONOMY_URL = "https://static.openfoodfacts.org/data/taxonomies/categories.json";
const OUT = "src/lib/offCategories.ts";

type Taxonomy = Record<string, { name?: Record<string, string>; parents?: string[] }>;

async function load(): Promise<Taxonomy> {
  const file = process.argv[2];
  if (file) return JSON.parse(readFileSync(file, "utf8"));
  const r = await fetch(TAXONOMY_URL);
  if (!r.ok) throw new Error(`Open Food Facts answered ${r.status}`);
  return (await r.json()) as Taxonomy;
}

const taxonomy = await load();

// Products carry every ancestor of their category too, so a broad tag like
// "snacks" matches far more foods than a leaf. Depth orders the list broadest
// first, which is the order suggestions are offered in.
const depths = new Map<string, number>();
function depth(id: string, seen = new Set<string>()): number {
  const known = depths.get(id);
  if (known !== undefined) return known;
  if (seen.has(id)) return 0;
  seen.add(id);
  const parents = (taxonomy[id]?.parents ?? []).filter((p) => taxonomy[p]);
  const d = parents.length ? 1 + Math.min(...parents.map((p) => depth(p, seen))) : 0;
  depths.set(id, d);
  return d;
}

// English-named categories only: product tags use the English id whenever
// the taxonomy has one, and the rule editor is in English.
const tags = Object.keys(taxonomy)
  .filter((id) => id.startsWith("en:") && taxonomy[id].name?.en)
  .map((id) => ({ slug: id.slice(3), depth: depth(id) }))
  .filter((t) => !t.slug.includes("|"))
  .sort((a, b) => a.depth - b.depth || a.slug.localeCompare(b.slug));

const today = new Date().toISOString().slice(0, 10);
writeFileSync(
  OUT,
  `// Generated by scripts/build-categories.ts on ${today} from the Open Food
// Facts category taxonomy: ${tags.length} English categories, broadest first.
// Do not edit by hand.
export const OFF_CATEGORIES: string[] = ${JSON.stringify(tags.map((t) => t.slug).join("|"))}.split("|");
`,
);
console.log(`Wrote ${tags.length} categories to ${OUT}`);
